CREATE TABLE IF NOT EXISTS users_relations_status (
    status_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) UNIQUE NOT NULL,
    login VARCHAR(100) NOT NULL,
    name VARCHAR(100),
    birthdate DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS films_genres (
    genre_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
    description VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS film_rates (
    rate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(10) UNIQUE NOT NULL,
    description VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS films (
    film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(200) NOT NULL,
    release_date DATE NOT NULL,
    duration INT NOT NULL,
    rate_id BIGINT NOT NULL DEFAULT 'unknown',
    FOREIGN KEY (rate_id) REFERENCES film_rates(rate_id)
);

CREATE TABLE IF NOT EXISTS film_genre_relations (
    film_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    PRIMARY KEY (film_id, genre_id),
    FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE,
    FOREIGN KEY (genre_id) REFERENCES films_genres(genre_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS users_relations (
    relation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    related_id BIGINT NOT NULL,
    relation_status_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (related_id) REFERENCES users(user_id),
    FOREIGN KEY (relation_status_id) REFERENCES users_relations_status(status_id)
);

CREATE TABLE IF NOT EXISTS film_likes (
    like_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    film_id BIGINT NOT NULL,
    mark INT NOT NULL,
    like_date DATETIME NOT NULL,
    FOREIGN KEY (user_id) REFERENCES "USERS"(user_id),
    FOREIGN KEY (film_id) REFERENCES "FILMS"(film_id)
);